name: Build Source Docs

on:
  push:
    branches: [ source-docs ]

jobs:
  build-source-docs:
    runs-on: ubuntu-latest  
    name: Build Source Documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Sphinx docs
        run: |
          sudo apt-get install python3-sphinx
          cd Source/docs_sphinx
          make html
     
